version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: containers/mysql/Dockerfile
    container_name: mysql-container
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "13306:3306"
    env_file:
      - .env.prod
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD"
      # ヘルスチェックのインターバルは10秒
      interval: 10s
      # タイムアウト時間は10秒
      timeout: 10s
      # リトライ回数は3回
      retries: 3
      # ヘルスチェックが失敗しても無視する時間は60秒
      start_period: 60s

  app:
    build:
      context: .
      dockerfile: containers/django/Dockerfile
    container_name: django-rest-container
    volumes:
      - .:/app
      - ./static:/static
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.prod
    command: sh /app/entrypoint.sh
  web:
    # コンテナ名をnginx-containerに指定
    container_name: nginx-container
    # NginxのDockerfileをビルドする
    build:
      # ビルドコンテキストはカレントディレクトリ
      context: .
      dockerfile: containers/nginx/Dockerfile
    # ボリュームを指定
    # ローカルの/staticをコンテナの/staticにマウントする
    volumes:
      - ./collected_staticfiles:/static
    # ローカルの80番ボートをコンテナの80番ポートとつなぐ
    ports:
      - "80:80"
    # 先にappを起動してからwebを起動する
    depends_on:
      - app

volumes:
  db_data:
  static: